### ISSUE TITLE
invoice = false nor working + Wrong day to extract if monday, before 13:01

### ISSUE THREAD

**Issue by SharpBCD** [JorgenVatle/bnr-exchange-history#1]
Tried without `invoice` and with `invoice = false` (and true, just to see the difference. Same result.
Check pictures

![image](https://user-images.githubusercontent.com/31144210/95694203-5b568c80-0c39-11eb-8e90-929978307956.png)
![image](https://user-images.githubusercontent.com/31144210/95694222-7d500f00-0c39-11eb-9508-7e5be2a0a06b.png)

**Comment by SharpBCD** [comment]
Update: today, the rate were correct. Could be a problem with local_time and if the request is made close to 11pm it takes the wrong date?

**Comment by JorgenVatle** [comment]
That's interesting. I'm having some trouble reproducing the issue on my end. If you run into the issue again or manage to reproduce it, let me know so I can further look into this for you. Hopefully there's something we could write up some tests for. 🙌

In the meantime, I'll go ahead and tweak how we compare dates to hopefully eliminate any inconsistencies with how Node handles dates.

**Comment by SharpBCD** [comment]
aannd... nope. Every Sunday it takes the rates from Thursday, not Friday.
And the request is made at 13:10, Bucharest time. :(

**Comment by SharpBCD** [comment]
![image](https://user-images.githubusercontent.com/31144210/99313027-8bf89a00-2867-11eb-8c9c-52aa7e7bb3c5.png)

![image](https://user-images.githubusercontent.com/31144210/99312963-78e5ca00-2867-11eb-81da-bbf58674c302.png)

can be noticed that today (monday) is wrong, as well. While for weekend is not so important, for working days it really matter.
Can we fix it?
P.S. I attached the creation timestamp to notice the hour of query.

**Comment by JorgenVatle** [comment]
Should've been fixed with 02672d5e846487cc0b55158f81c13a50d299cb26 👍
